matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      before_install:
        - docker build -t docker-react -f Dockerfile.test.react .
      script:
        - docker run docker-react npm run test -- --coverage
    - language: generic
      sudo: required
      services:
        - docker
      before_install:
        - docker build -t docker-python -f Dockerfile.test.python .
      script:
        - docker run docker-python python -m pytest tests
    - language: generic
      sudo: required
      services: docker
      before_install:
        - docker -v
      script:
        - docker-compose run nightwatch